---
title: "Households by type"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, message = F, warning = F)
```

```{r}
library(tidyverse)
library(tidycensus)
library(janitor)
library(cwi)
library(camiller)
```

These don't change much year over year, so I think 2000, 2010, and 2018 should be sufficient to make our point.

# Fetch

```{r}
tbls <- ext_table_nums[c("family", "children")]

fetch18 <- tbls %>% map(~multi_geo_acs(table = ., year = 2018, new_england = F) %>% 
												label_acs() %>%
												select(-GEOID) %>% 
												rename(name = NAME) %>% 
												group_by(level, name))

fetch10 <- tbls %>% map(~multi_geo_acs(table = ., year = 2010, new_england = F) %>% 
												label_acs() %>%
												select(-GEOID) %>% 
												rename(name = NAME) %>% 
												group_by(level, name))

fetch00 <- multi_geo_decennial(table = "P018", year = 2000)
```

# Clean
```{r}
family <- bind_rows(fetch18$family, fetch10$family) %>%
  mutate(label = as.factor(label) %>% fct_inorder()) %>%
  group_by(level, name, year) %>%
  add_grps(list(total_households = 1, living_alone = 8, other_nonfamily = 9), group = label, moe = moe)

children <- bind_rows(fetch18$children, fetch10$children) %>%
  mutate(label = as.factor(label) %>% fct_inorder()) %>%
  group_by(level, name, year) %>%
  add_grps(list(married_w_kids = 3, married_no_kids = 7, single_w_kids = c(10, 16), other_family = c(14, 20)), group = label, moe = moe)

hh00 <- fetch00 %>%
  label_decennial(year = 2000) %>% 
  group_by(level, name = NAME) %>% 
  add_grps(list(total_households = 1, living_alone = 2, married_w_kids = 8, married_no_kids = 9, single_w_kids = c(12, 15), other_households = c(13, 16, 17)), group = label, estimate = value) %>%
  mutate(year = 2000)

household_type <- bind_rows(family, children) %>%
  add_grps(list(other_households = c(3, 7)), group = label) %>%
  bind_rows(family %>% filter(label != "other_nonfamily")) %>%
  bind_rows(children %>% filter(label != "other_family")) %>%
  mutate(label = as.factor(label) %>% fct_relevel("total_households", "married_w_kids", "married_no_kids", "single_w_kids", "living_alone", "other_households")) %>% 
	select(-moe, value = estimate) %>%
	bind_rows(hh00) %>% 
	rename(group = label) %>% 
  ungroup() %>%
  group_by(level, name, year) %>%
  calc_shares(group = group, denom = "total_households", estimate = value) %>%
  mutate(year = as.factor(year),
  			 group = as.factor(group) %>%
           fct_relevel("married_w_kids", "married_no_kids", "single_w_kids", "living_alone", "other_households")) %>%
  ungroup()

write_csv(household_type, "../output_data/household_type_2000_2018.csv")
```

# Calculate change

```{r}
household_type_change <- household_type %>%
	select(-share) %>%
	group_by(level, group) %>%
	arrange(name, year, group) %>%
	mutate(diff = value - lag(value, default = first(value))) %>%
	arrange(level, year, group) %>%
	rename(change_from_prev_data_year = diff)
	
household_type_change %>% 
	write_csv("../output_data/household_type_change_2000_2018.csv")
```

```{r fig.height=5, fig.width=6.25}
set.seed(13)

household_type_change %>% 
	ungroup() %>% 
	mutate(group = as.character(group),
				 group = str_replace_all(group, "_", " "),
				 group = str_replace(group, "w", "with"),
				 group = str_replace(group, "no", "without"),
				 group = str_to_sentence(group)) %>% 
	mutate(group = as.factor(group) %>% 
				 	fct_relevel(.,  "Total households", "Living alone", "Married with kids", "Married without kids", "Single with kids", "Other households")) %>% 
	filter(level != "3_towns", group != "Total households") %>% 
	select(-level, -change_from_prev_data_year) %>% 
	mutate(year = as.factor(year)) %>% 
	filter(name == "Connecticut") %>% 
	ggplot(aes(year, value, group = group)) +
	geom_vline(aes(xintercept = year), size = .5, color = "grey70") +
	geom_point(aes(color = group), size = 4, alpha = .8) +
	geom_line(aes(color = group), size = 1, alpha = .8) +
	ggrepel::geom_text_repel(aes(label = scales::comma(value, accuracy = 1)), segment.colour = NA, vjust = -1.4, family = "Roboto Condensed") +
	scale_y_continuous(expand = expansion(mult = c(.1, .1))) +
	hrbrthemes::theme_ipsum_rc() +
	guides(color = guide_legend(title = "", override.aes = list(linetype = 0))) +
	labs(title = "Households by type, 2000–2018",
			 subtitle = "Connecticut",
			 x = "", y = "") +
	theme(plot.title.position = "plot",
				axis.text.y = element_blank(),
				panel.grid.major = element_blank(),
				panel.grid.minor = element_blank(),
				axis.text.x = element_text(colour = "black"),
				legend.position = "bottom")
```

```{r}
household_type_change %>% 
	ungroup() %>% 
	filter(level != "3_towns") %>% 
	mutate(group = as.character(group),
				 group = str_replace_all(group, "_", " "),
				 group = str_replace(group, "w", "with"),
				 group = str_replace(group, "no", "without"),
				 group = str_to_sentence(group)) %>% 
	mutate(group = as.factor(group) %>% 
				 	fct_relevel(.,  "Total households", "Living alone", "Married with kids", "Married without kids", "Single with kids", "Other households")) %>% 
	select(-level, -change_from_prev_data_year) %>% 
	pivot_wider(id_cols = c("name", "group"), names_from = year, values_from = value) %>% 
	group_by(name, group) %>% 
	mutate(diff = (`2018` - `2000`) / `2000`,
				 pct = scales::percent(diff, accuracy = 1),
				 x2000 = scales::comma(`2000`, accuracy = 1),
				 x2018 = scales::comma(`2018`, accuracy = 1)) %>% 
	select(Name = name, `Household type` = group, `Estimate, 2000` = x2000, `Estimate, 2018` = x2018, `Percent change` = pct) %>% 
	arrange(Name, `Household type`) %>% 
	kableExtra::kable()
```

```{r fig.width=10, fig.height=10}
household_type_change %>% 
	ungroup() %>% 
	filter(level != "3_towns") %>% 
	mutate(group = as.character(group),
				 group = str_replace_all(group, "_", " "),
				 group = str_replace(group, "w", "with"),
				 group = str_replace(group, "no", "without"),
				 group = str_to_sentence(group)) %>% 
	mutate(group = as.factor(group) %>% 
				 	fct_relevel(.,  "Total households", "Living alone", "Married with kids", "Married without kids", "Single with kids", "Other households")) %>% 
	select(-level, -change_from_prev_data_year) %>% 
	pivot_wider(id_cols = c("name", "group"), names_from = year, values_from = value) %>% 
	group_by(name, group) %>% 
	mutate(diff = (`2018` - `2000`)) %>%
	#mutate(diff = (`2018` - `2000`) / `2000`) %>% 
	select(name, group, diff) %>% 
	ggplot(aes(diff, group)) +
	geom_vline(xintercept = 0, size = .25, alpha = .8) +
	geom_col(aes(fill = group), width = .75, position = "identity") +
	geom_text(aes(label = scales::comma(diff, accuracy = 1)), hjust = "inward", position = "identity", family = "Roboto Condensed", size = 4) +
	scale_x_continuous(expand = expansion(mult = c(.15,.05))) +
	facet_wrap(facets = "name", scales = "free_x") +
	hrbrthemes::theme_ipsum_rc() +
	guides(fill = guide_legend(title = "")) +
	labs(title = "Change in households by type, 2000–2018",
			 subtitle = "Connecticut",
			 x = "", y = "") +
	theme(plot.title.position = "plot",
				axis.text.y = element_text(colour = "black"),
				strip.text.x = element_text(hjust = .5),
				panel.grid.minor = element_blank(),
				panel.grid.major = element_blank(),
				axis.text.x = element_blank(),
				legend.position = "none")
```